### PR TITLE
fix request context cancellation is ignored when retryBackoff (#539)

### LINKED ISSUE #539: [BUG] Request context cancellation is ignored when `retryBackoff` is configured
When `retryBackoff` is configured, the client sleeps between retries and ignores request context cancellation.

In short, the same issue as the one in the origin [ES client](https://github.com/elastic/go-elasticsearch/issues/300). The fix has not yet been ported to the [OpenSearch client](https://github.com/opensearch-project/opensearch-go/blob/216cc6fdba9c94b819b45afb3ed7eed67306384d/opensearchtransport/opensearchtransport.go#L381-L384)

### PR DESCRIPTION
**Pull request by zhyu**
Fixes #539 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by dblock** [comment]
Thanks.

I'd love some additions to the docs on retries and back offs, can be a separate topic in https://github.com/opensearch-project/opensearch-go/tree/main/guides or https://github.com/opensearch-project/opensearch-go/blob/main/USER_GUIDE.md, but something generic enough on configuring the client?

Since you reference Elastic in https://github.com/opensearch-project/opensearch-go/issues/539, can you please confirm that you're not bringing in any non-APLv2 code in this project?

**Review by dblock — CHANGES_REQUESTED** [review]
To fix DCO, run `git commit -s --amend`. Thanks.

**Comment by zhyu** [comment]
> I'd love some additions to the docs on retries and back offs

I added a very simple doc about configuring the client with retries and backoffs.

> can you please confirm that you're not bringing in any non-APLv2 code in this project?

Yes, I can confirm that.

I also found the client will sleep when the last retry failed, which seems not expected. So I pushed another fix (https://github.com/opensearch-project/opensearch-go/pull/540/commits/8b2649cedd28bdae1b57067beef3840cdbffa2cc) for it. Please have a look. Thanks!

**Comment by dblock** [comment]
> I also found the client will sleep when the last retry failed, which seems not expected. So I pushed another fix ([8b2649c](https://github.com/opensearch-project/opensearch-go/commit/8b2649cedd28bdae1b57067beef3840cdbffa2cc)) for it.

Good find. This deserves its own test, too.

**Review by dblock — DISMISSED** [review]
Looks great. @Jakob3xD should take a look / merge, I am not super familiar with ways to do this in Go, I might be missing something.

**Review by Jakob3xD — DISMISSED** [review]
Only a small nit about the indent of the guide but good to go.

**Review by dblock — DISMISSED** [review]
Merging, thanks!

I don't think we want an entire guide for retry and backoff. Maybe a "Configuration" doc that has a "Retries" section (and other configuration options)? @zhyu interested in (re)organizing things?

**Review by dblock — DISMISSED** [review]

**Comment by dblock** [comment]
@zhyu Can you please take a quick look at the failing integration tests?

```
=== RUN   TestNodes/Stats/without_request
    api_nodes_test.go:182: 
        	Error Trace:	/home/runner/work/opensearch-go/opensearch-go/internal/test/helper.go:147
        	            				/home/runner/work/opensearch-go/opensearch-go/opensearchapi/api_nodes_test.go:182
        	Error:      	Should be empty, but was [{"op":"remove","path":"/nodes/QR8UfvZLSXmNJrK8ZCf0Pg/indices/search/search_idle_reactivate_count_total"}]
        	Test:       	TestNodes/Stats/without_request
```

I am not sure it's related, but could be. If it's a flake, check whether we already have an issue for it / open a new one.

**Comment by Jakob3xD** [comment]
> I am not sure it's related, but could be. If it's a flake, check whether we already have an issue for it / open a new one.

The tests are failing because the new opensearch release adds a new field. Not related to the PR.

**Review by Jakob3xD — APPROVED** [review]

**Pull request merged**
