### PR TITLE
Add opensearch 2.6.0, 2.7.0, 2.8.0 to compatibility test

### PR DESCRIPTION
**Pull request by Jakob3xD**
### Description
Add opensearch 2.6.0, 2.7.0, 2.8.0 to compatibility test

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by dblock** [comment]
Should we be concerned about failures with unreleased versions of OpenSearch?

**Review by dblock — APPROVED** [review]

**Comment by Jakob3xD** [comment]
> Should we be concerned about failures with unreleased versions of OpenSearch?

@dblock It seems to me that the current 3.0.0 Snapshot does not return a `X-Opensearch-Version` Header. I am not sure if this is expected but that is the reason of failure. So it is not related to this MR. It is more general as the dependency updates PRs are also failing with the same error.

**Comment by dblock** [comment]
That was added recently, wasn't it?
https://github.com/opensearch-project/OpenSearch/pull/8084/files

**Comment by Jakob3xD** [comment]
> That was added recently, wasn't it?

Yes, I was confused by the job output but the tests use the wrong want/expect order.
The tests only expect the application/json header but now also got the version header.

**Pull request merged**
