### PR TITLE
fix(issue-151): replace _template with _index_template

### PR DESCRIPTION
**Pull request by omurbekjk**
Signed-off-by: Omurbek Kadyrbekov [omurbek.jk@gmail.com](mailto:omurbek.jk@gmail.com)

### Description
Set correct path for index templates api
### Issues Resolved
Closes[#151]
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by VachaShah** [comment]
Thank you @omurbekjk! Can you please rebase with main to get the latest changes?

**Comment by wbeckler** [comment]
@omurbekjk are you interested in getting this merged? If so please take a look. Otherwise, I think we might want to close this for now.

**Comment by Jakob3xD** [comment]
The `_index_template` api is already implemented. This would make it duplicate. IMO this should either be removed with a breaking changes, as some users might use it or leave it as is until it gets removed from Opensearch.
More over replacing it would brake current client implementations as the request body is different.

https://github.com/opensearch-project/opensearch-go/blob/main/opensearchapi/api.indices.put_index_template.go
https://github.com/opensearch-project/opensearch-go/blob/main/opensearchapi/api.indices.delete_index_template.go

**Comment by VachaShah** [comment]
Closing this PR since `_index_template` APIs already exist in the go client as mentioned by @Jakob3xD. Please feel free to open a new PR if you think otherwise.

**Pull request closed without merging**
