### PR TITLE
Add changelog skiplabel on workflow with skip-changelog label

### PR DESCRIPTION
**Pull request by peterzhuamazon**
Signed-off-by: Peter Zhu <zhujiaxi@amazon.com>

### Description
Add changelog skiplabel on workflow with skip-changelog label

### Issues Resolved
https://github.com/opensearch-project/opensearch-go/pull/208#issuecomment-1372838786

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by dblock — APPROVED** [review]
Thanks!

**Comment by dblock** [comment]
@peterzhuamazon A related item is to get dependabot to add a bump change into CHANGELOG in its PRs. Want to take that too?

**Comment by peterzhuamazon** [comment]
> @peterzhuamazon A related item is to get dependabot to add a bump change into CHANGELOG in its PRs. Want to take that too?

Hi DB, you mean to say dependabot auto add entry to changelog.md?

**Review by VachaShah — APPROVED** [review]

**Comment by dblock** [comment]
> > @peterzhuamazon A related item is to get dependabot to add a bump change into CHANGELOG in its PRs. Want to take that too?
> 
> Hi DB, you mean to say dependabot auto add entry to changelog.md?

Yes, please!

**Pull request merged**
