### PR TITLE
Added govulncheck workflow

### PR DESCRIPTION
**Pull request by tannerjones4075**
Signed-off-by: Tanner Jones <alltechguyblog@gmail.com>

### CODE REVIEW

**Comment by tannerjones4075** [comment]
Any thoughts @dblock?

**Comment by dblock** [comment]
What does this do? :)

**Comment by tannerjones4075** [comment]
> What does this do? :)

1. It fetches the specified Go modules in the project
2. It checks for any known vulnerabilities in the Go modules by comparing against the Go vulnerability database.
3. It reports the vulnerabilities found

**Comment by dblock** [comment]
But we already have dependabot and friends, no?

Anyway I don't have anything against merging this PR! @Jakob3xD WDYT?

**Review by VachaShah — APPROVED** [review]

**Comment by tannerjones4075** [comment]
How can I get access to the results of the govulncheck?

**Pull request merged**
