### PR TITLE
Revert "Draft: Add Err() function to Response for detailed errors (#2…

### PR DESCRIPTION
**Pull request by VachaShah**
…46)"

This reverts commit 8d3cf4dd6e872f5c9fc50408ca74dc7c06e9b490.

### Description
Reverting the breaking change in 2.3 branch so that a new 2.x version can be released. The main branch tracks the 3.0 changes with this breaking change.

### Issues Resolved
_List any issues this PR will resolve, e.g. Closes [...]._ 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by VijayanB — APPROVED** [review]

**Comment by dblock** [comment]
Resolve changelog?

**Comment by dblock** [comment]
Why do we need to release another 2.x? Can we release 3.x and move forward?

**Comment by VachaShah** [comment]
> Why do we need to release another 2.x? Can we release 3.x and move forward?

2.x has some security fixes which need to go out and since it had some new features too, so the next 2.x version. If we want to move to 3.x, we could release this last version and mention in the README that for new features, the user can move to the 3.x line.

WDYT @dblock?

**Comment by VachaShah** [comment]
Also @Jakob3xD would love to get your eyes on this change since it reverts the Err() related changes from several PRs. Thank you!

**Comment by dblock** [comment]
> > Why do we need to release another 2.x? Can we release 3.x and move forward?
> 
> 2.x has some security fixes which need to go out and since it had some new features too, so the next 2.x version. If we want to move to 3.x, we could release this last version and mention in the README that for new features, the user can move to the 3.x line.
> 
> WDYT @dblock?

I'm fine with it. 

I guess I don't understand why we need to revert this feature from 2.3. Can we release the next 2.x with it?

**Comment by Jakob3xD** [comment]
> I guess I don't understand why we need to revert this feature from 2.3. Can we release the next 2.x with it?

IIRC we did not want to make a 2.x release with it because it is a braking changes.
Maybe we want to wait with the 3.x release for the restructure of this lib, but this will take some time as I am currently busy with managing opensearch clusters.


The MR LGTM.

**Review by dblock — APPROVED** [review]

**Comment by VachaShah** [comment]
Thank you @dblock and @Jakob3xD! I added an update for the 2.3.0 version in PR #325 that is described above.

**Pull request merged**
