### PR TITLE
Correct CurlLogger's URL to actual destination

### PR DESCRIPTION
**Pull request by dekimsey**
### Description
The CurlLogger hardcodes `http://localhost:9200`. This change instead uses the given configuration values.
 
### Issues Resolved
n/a
 
### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by VachaShah** [comment]
@dekimsey Thank you for this change! Can you please rebase and get in the latest changes from main?

**Comment by dekimsey** [comment]
Sorry for not seeing your request @dblock, it has been a busy year and I missed your request. I'm updating it now. I also fixed the tests to validate the change.

**Comment by dekimsey** [comment]
@VachaShah I believe this is complete now. Let me know what you think, thank you for pinging me on this!

**Review by dblock — APPROVED** [review]

**Comment by dblock** [comment]
Apologies for having missed this. I resolved the CHANGELOG conflict, let's merge this once CI passes.

**Review by VachaShah — APPROVED** [review]

**Pull request merged**
