### PR TITLE
Fix search request missing a slash when no indices are given

### PR DESCRIPTION
**Pull request by Jakob3xD**
### Description
Add missing `/ ` for search requests when not searching specific indices.

### Issues Resolved
Closes https://github.com/opensearch-project/opensearch-go/issues/470

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by Jakob3xD** [comment]
Draft as I am waiting for a reply on the issue to maybe adjust the integration tests.

**Comment by dblock** [comment]
Definitely needs tests! Thanks for fixing this.

**Comment by dblock** [comment]
@Jakob3xD Want to finish this?

**Comment by Jakob3xD** [comment]
> @Jakob3xD Want to finish this?

Well, I can mark it as ready but I have no idea for testing this in a useful way for all endpoints.
We could add a unit test for each endpoint creating a requests and calling the `GetRequest()` function and check the URL if it stats with a `/`. But I am not sure this works.

**Comment by dblock** [comment]
> > @Jakob3xD Want to finish this?
> 
> Well, I can mark it as ready but I have no idea for testing this in a useful way for all endpoints. We could add a unit test for each endpoint creating a requests and calling the `GetRequest()` function and check the URL if it stats with a `/`. But I am not sure this works.

I would at a minimum add a test for this specific endpoint (this bug). But something that iterates over all APIs would be better.

**Review by dblock — DISMISSED** [review]

**Review by dblock — APPROVED** [review]

**Pull request merged**
