### PR TITLE
Fix: integration tests with unreleased version of OpenSearch.

### PR DESCRIPTION
**Pull request by dblock**
### Description

Similar to https://github.com/opensearch-project/opensearch-py/pull/798, needs a different JDK depending on branch.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by dblock** [comment]
I am confused to how this passed before and is failing now. @Jakob3xD maybe?

```
2024-08-19T23:41:33.1991069Z     --- FAIL: TestCatClient/ValidateResponse (0.08s)
2024-08-19T23:41:33.1992267Z         --- PASS: TestCatClient/ValidateResponse/Aliases (0.00s)
2024-08-19T23:41:33.1993646Z         --- PASS: TestCatClient/ValidateResponse/Allocation (0.00s)
2024-08-19T23:41:33.1994995Z         --- FAIL: TestCatClient/ValidateResponse/ClusterManager (0.00s)
2024-08-19T23:41:33.1996289Z         --- PASS: TestCatClient/ValidateResponse/Count (0.03s)
2024-08-19T23:41:33.1997687Z         --- PASS: TestCatClient/ValidateResponse/FieldData (0.00s)
2024-08-19T23:41:33.1998965Z         --- PASS: TestCatClient/ValidateResponse/Health (0.00s)
2024-08-19T23:41:33.2000166Z         --- PASS: TestCatClient/ValidateResponse/Indices (0.01s)
2024-08-19T23:41:33.2001522Z         --- PASS: TestCatClient/ValidateResponse/Master (0.00s)
2024-08-19T23:41:33.2002819Z         --- PASS: TestCatClient/ValidateResponse/NodeAttrs (0.00s)
2024-08-19T23:41:33.2003999Z         --- PASS: TestCatClient/ValidateResponse/Nodes (0.00s)
2024-08-19T23:41:33.2005430Z         --- PASS: TestCatClient/ValidateResponse/PendingTasks (0.00s)
2024-08-19T23:41:33.2006730Z         --- PASS: TestCatClient/ValidateResponse/Plugins (0.00s)
2024-08-19T23:41:33.2007937Z         --- PASS: TestCatClient/ValidateResponse/Recovery (0.01s)
2024-08-19T23:41:33.2009401Z         --- PASS: TestCatClient/ValidateResponse/Repositories (0.00s)
2024-08-19T23:41:33.2010716Z         --- PASS: TestCatClient/ValidateResponse/Segments (0.00s)
2024-08-19T23:41:33.2012461Z         --- PASS: TestCatClient/ValidateResponse/Shards (0.01s)
2024-08-19T23:41:33.2014078Z         --- PASS: TestCatClient/ValidateResponse/Tasks (0.00s)
2024-08-19T23:41:33.2015359Z         --- PASS: TestCatClient/ValidateResponse/Templates (0.00s)
2024-08-19T23:41:33.2016688Z         --- PASS: TestCatClient/ValidateResponse/ThreadPool (0.01s)
2024-08-19T23:41:33.2017608Z === RUN   TestClusterClient
2024-08-19T23:41:33.2018255Z === RUN   TestClusterClient/Reroute
2024-08-19T23:41:33.2018998Z === RUN   TestClusterClient/Reroute/with_request
2024-08-19T23:41:33.2019843Z === RUN   TestClusterClient/Reroute/inspect
2024-08-19T23:41:33.2020559Z === RUN   TestClusterClient/State
2024-08-19T23:41:33.2021304Z === RUN   TestClusterClient/State/with_nil_request
2024-08-19T23:41:33.2022224Z === RUN   TestClusterClient/State/with_request
2024-08-19T23:41:33.2023258Z === RUN   TestClusterClient/State/inspect
2024-08-19T23:41:33.2024035Z === RUN   TestClusterClient/PutDecommission
2024-08-19T23:41:33.2024912Z === RUN   TestClusterClient/PutDecommission/inspect
2024-08-19T23:41:33.2025830Z === RUN   TestClusterClient/GetDecommission
2024-08-19T23:41:33.2026715Z === RUN   TestClusterClient/GetDecommission/with_request
2024-08-19T23:41:33.2027789Z     api_cluster_test.go:243: 
2024-08-19T23:41:33.2029633Z         	Error Trace:	/home/runner/work/opensearch-go/opensearch-go/go-client/opensearchapi/api_cluster_test.go:243
2024-08-19T23:41:33.2032223Z         	Error:      	Expected nil, but got: &opensearch.Error{Err:"no handler found for uri [/_cluster/decommission/awareness/test/_status] and method [GET]"}
2024-08-19T23:41:33.2034260Z         	Test:       	TestClusterClient/GetDecommission/with_request
```

**Comment by Jakob3xD** [comment]
Got this endpoint maybe removed in the upstream Opensearch?

**Comment by dblock** [comment]
> Got this endpoint maybe removed in the upstream Opensearch?

It's the other way around. The `master` concept was [deprecated in 2.x, superseded by `cluster manager`](https://opensearch.org/blog/Adopting-inclusive-language-across-OpenSearch/). The `SkipIfBelowVersion` was not implemented correctly, should have fixed this the first time integration tests started failing. 

The reason why tests were passing in 1.x before is because we were actually running against OpenSearch 3.x (main). The workflow is simply incorrect and uses `matrix.entry.opensearch_ref` which doesn't exist, and should have been `matrix.opensearch_ref`. Check out https://github.com/opensearch-project/opensearch-go/actions/runs/10265860449/job/28402939845.

```
2024-08-06T11:47:38.0646042Z [2024-08-06T11:47:38,062][INFO ][o.o.n.Node               ] [fv-az1498-913] version[3.0.0-SNAPSHOT], pid[2328],
```

**Comment by dblock** [comment]
@Jakob3xD this is ready

**Review by Jakob3xD — APPROVED** [review]

**Pull request merged**
