### PR TITLE
Fix ISM Plugin Transitions Conditions struct (#555)

### PR DESCRIPTION
**Pull request by emtammaru**
### Issues Resolved
Closes https://github.com/opensearch-project/opensearch-go/issues/555

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by dblock — APPROVED** [review]
This LGTM.

**Comment by dblock** [comment]
One more reason for #284, maybe @emtammaru you have some thoughts as a first time contributor.

**Comment by emtammaru** [comment]
Thanks for the quick turnaround on this fix @dblock.  Regarding https://github.com/opensearch-project/opensearch-go/issues/284, that would probably be best if all the types could be generated from a single spec :)

**Comment by dblock** [comment]
Maybe you're interested in helping? :) wink wink

**Comment by emtammaru** [comment]
image

Will think about it haha maybe on a rainy day.  Has anyone else started on it yet?

**Comment by dblock** [comment]
> Has anyone else started on it yet?

I don't believe so.

**Pull request merged**
