### PR TITLE
Fixing paths for some APIs

### LINKED ISSUE #132: [BUG] UpdateRequest never update.
**What is the bug?**
the api.update.go using wrong HTTP request path.

**How can one reproduce the bug?**
Steps to reproduce the behavior: create UpdateRequest and execute it.

**What is the expected behavior?**
Swap line 101 & 103 of "opensearchapi/api.update.go".

**What is your host/environment?**
 - OS: macos
 - Version 12
 - Plugins

**Do you have any screenshots?**
None.

**Do you have any additional context?**
None

### PR DESCRIPTION
**Pull request by VachaShah**
Signed-off-by: Vacha Shah <vachshah@amazon.com>

### Description
Fixing url paths for some APIs after type removal. 

### Issues Resolved
Closes #132 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by dblock** [comment]
I am new to this codebase and don't quite understand what's going on :) Looks like the PR swaps the order of `_DocumentId` and, for example, `_create`? Help me understand like a 2yo?

**Comment by VachaShah** [comment]
> I am new to this codebase and don't quite understand what's going on :) Looks like the PR swaps the order of `_DocumentId` and, for example, `_create`? But we just removed types ... Help me understand like a 2yo?

With the removed types, the paths that now remain are in the swapped order.

For `create`, https://github.com/opensearch-project/OpenSearch/blob/main/rest-api-spec/src/main/resources/rest-api-spec/api/create.json#L11
For `exists_source`, https://github.com/opensearch-project/OpenSearch/blob/main/rest-api-spec/src/main/resources/rest-api-spec/api/exists_source.json#L11
For `explain`, https://github.com/opensearch-project/OpenSearch/blob/main/rest-api-spec/src/main/resources/rest-api-spec/api/explain.json#L11
For `get_source`, https://github.com/opensearch-project/OpenSearch/blob/main/rest-api-spec/src/main/resources/rest-api-spec/api/get_source.json#L11
For `termvectors`, https://github.com/opensearch-project/OpenSearch/blob/main/rest-api-spec/src/main/resources/rest-api-spec/api/termvectors.json#L11
For `update`, https://github.com/opensearch-project/OpenSearch/blob/main/rest-api-spec/src/main/resources/rest-api-spec/api/update.json#L11

**Review by dblock — APPROVED** [review]

**Comment by dblock** [comment]
Thanks. I suppose we don't have integration tests for this? I'd expect some to fail.

**Comment by VachaShah** [comment]
> Thanks. I suppose we don't have integration tests for this? I'd expect some to fail against OpenSearch 2.x. Open an issue at least?

Yes currently these APIs are not part of the integration test. I have created #135 to add this issue.

**Review by saratvemulapalli — APPROVED** [review]

**Pull request merged**
