### PR TITLE
Fixes opensearch-project/opensearch-go#522

### PR DESCRIPTION
**Pull request by martingrzzler**
### Description
Add test for 429 example response. Handle the error with an added sentinel.

### CODE REVIEW

**Comment by dblock** [comment]
Add a line to CHANGELOG please and we're good to go.

**Comment by dblock** [comment]
Also see https://github.com/opensearch-project/opensearch-go/issues/522#issuecomment-2047653280

**Review by dblock — APPROVED** [review]
Looks good. Would be great to have a section in the user guide on error handling.

**Comment by dblock** [comment]
@martingrzzler You have to sign all your commits with DCO please (`git commit -s --amend` and force push).

**Review by Jakob3xD — APPROVED** [review]

**Pull request merged**
