### PR TITLE
Format with prettier

### PR DESCRIPTION
**Pull request by harrisonhjones**
### Description

Just a simple "let's format the markdown files" PR. Ran `npx prettier --prose-wrap "always" -w *.md` and committed the results.

### Issues Resolved

None

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by dblock — CHANGES_REQUESTED** [review]
We've been keeping Markdown files without the 80 column thing because it makes diffs unreadable - https://code.dblock.org/2021/06/07/to-wrap-or-not-to-wrap-in-markdown.html. Otherwise down with prettier for code?

**Comment by harrisonhjones** [comment]
Got it. I'm fairly sure prettier can't help with Go (that's what `go fmt` is for) bit prettier _can_ help with keeping markdown files consistent. I can re-run w/o prose-wrap to address your wrap concern.

**Comment by harrisonhjones** [comment]
I've rebased off of main and re-run w/o the prose wrap

**Review by dblock — APPROVED** [review]

**Comment by dblock** [comment]
Merging this, cause it looks ... prettier.

I'd like this to become part of CI. I also found https://github.com/opensearch-project/.github/issues/66 that was opened a while ago asking for the same across the org. Maybe we can standardize this linter (or another) across the org? Care to comment on that issue and maybe try PRing something into .github?

**Pull request merged**
