### PR TITLE
Add setting for allow_leading_wildcard to search

### PR DESCRIPTION
**Pull request by nevins-b**
### Description
Allow for setting, disabling, `allow_leading_wildcard` on a search

### Issues Resolved
_List any issues this PR will resolve, e.g. Closes [...]._ 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by dblock** [comment]
Thanks! Happy to take this with some tests, please?

**Comment by nevins-b** [comment]
@dblock Sure, I didn't see a place to add tests. I could add something to the benchmark tests but that didn't feel right. Suggestion of where I would add some?

**Comment by dblock** [comment]
Not a go expert nor have I looked in detail into opensearch-go to say where those tests should go, but looks like there's a bunch of tests that _are_ running (https://github.com/opensearch-project/opensearch-go/runs/6070092469?check_suite_focus=true). I'd like us not to merge untested code, so if you need to introduce a new set of tests and just test this one addition, let's do it?

**Comment by VachaShah** [comment]
@nevins-b Thank you for this PR! May be the tests can go [here](https://github.com/opensearch-project/opensearch-go/blob/main/opensearchapi/opensearchapi_integration_test.go#L44)?

**Comment by wbeckler** [comment]
Hi @nevins-b, do you think you'll want this merged? If nobody adds tests or moves this forward, I propose we close this PR.

**Comment by Jakob3xD** [comment]
While looking into the PR I noticed that `allow_leading_wildcard` does not seems to be a parameter for a search request.
`allow_leading_wildcard` is a filed of `query_string` in the search body. The body is given via the user so adding this to search prams would not work. https://opensearch.org/docs/latest/query-dsl/full-text/query-string/

I suggest closing the PR. @wbeckler

**Comment by wbeckler** [comment]
I'm okay with closing this. Any other maintainers have a thought?

**Pull request closed without merging**
